import { Scenario } from '../types'

export const DEFAULT_SCENARIO: Scenario = {
  scenario: {
    name: 'メインシナリオ',
    startAge: 40,
    endAge: 90,
    minimumCashBuffer: 3_000_000,
    investmentReturnRate: 0.03,
    inflationRate: 0.01,
  },
  loan: {
    principal: 30_000_000,
    downPayment: 0,
    startAge: 40,
    loanTermYears: 35,
    repaymentType: 'equal_payment',
    rateSchedule: [{ fromYear: 1, rate: 0.01 }],
    bonusMonthlyEquivalent: 0,
  },
  careerStages: [
    {
      fromAge: 40,
      toAge: 64,
      workStyle: 'employee',
      salaryInputMode: 'gross',
      grossSalaryAnnual: 6_000_000,
      bonusAnnual: 0,
      sideIncomeAnnual: 0,
    },
    {
      fromAge: 65,
      toAge: 90,
      workStyle: 'retired',
      retirementNationalPensionAnnual: 780_000,
      retirementEmployeesPensionAnnual: 600_000,
      retirementOtherIncomeAnnual: 0,
    },
  ],
  tax: {
    mode: 'simple_auto',
    basicDeductionAnnual: 480_000,
    spouseDeductionAnnual: 0,
    dependentDeductionAnnual: 0,
    lifeInsuranceDeductionAnnual: 0,
    earthquakeInsuranceDeductionAnnual: 0,
    medicalDeductionAnnual: 0,
    otherDeductionAnnual: 0,
    housingLoanDeductionAnnual: 0,
    housingLoanDeductionMode: 'auto' as const,
    housingLoanScheme: 'eco' as const,
    residentTaxLagEnabled: false,
  },
  housing: {
    fixedAssetTaxAnnual: 200_000,
    cityPlanningTaxAnnual: 50_000,
    homeInsuranceAnnual: 50_000,
    homeInsuranceDeductible: false,
    maintenanceAnnual: 150_000,
    otherHousingCostAnnual: 0,
  },
  living: {
    monthlyBaseCost: 250_000,
    monthlyUtilityCost: 20_000,
    educationCostAnnual: 0,
    carCostAnnual: 200_000,
    otherFixedCostAnnual: 0,
    monthlyRetirementCost: 200_000,
  },
  assets: {
    initialCash: 5_000_000,
    initialLiquidAssets: 2_000_000,
    initialNisaBalance: 0,
    initialSemiLiquidAssets: 0,
    initialRetirementAssets: 0,
    annualSavingsContribution: 0,
    annualNisaContribution: 0,
    emergencyUsableRatio: 0.7,
    annualRetirementDrawdown: 0,
    nisaStockRatio: 0,
    liquidStockRatio: 0,
    stockDividendYield: 0.03,
  },
  spouseCareerStages: [],
  events: [],
  strategy: {
    prepayments: [],
    targetPayoffAge: 75,
    stopPrepaymentIfCashBelowBuffer: true,
  },
  mutualAid: {
    smallBusinessMutualPayoutMethod: 'lump_sum',
    smallBusinessMutualAnnuityYears: 10,
  },
  homeOfficeExpense: {
    businessSpaceRatio: 0,
    utilityRatio: 0,
    buildingPrice: 0,
    buildingUsefulLife: 22,
  },
}
